### ISSUE TITLE
Arquivado?

### ISSUE THREAD

**Issue by xipanca** [Rechdan/W2.Server.Node#1]
O projeto está parado a um tempo, desistiu ou apenas está parado mesmo?
É a primeira vez que vejo um projeto em node que é algo que me sinto confortável em trabalhar, mas, ainda está no início, aí não consegui aprender sobre tudo, venho da área de react

**Comment by Rechdan** [comment]
Só parado mesmo, ainda penso em voltar e dar uma melhorada brutal nisso daqui.

**Comment by xipanca** [comment]
Espero que sim, fico no aguardo
